/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_ggrsrenderer_free: (a: number, b: number) => void;
export const ggrsrenderer_computeLayout: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const ggrsrenderer_computeLayoutViewport: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => void;
export const ggrsrenderer_computeLayoutWithMeasurer: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const ggrsrenderer_computeSkeleton: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const ggrsrenderer_computeTicksForRange: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const ggrsrenderer_getStaticChrome: (a: number, b: number) => void;
export const ggrsrenderer_getStreamLayout: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const ggrsrenderer_getViewChrome: (a: number, b: number) => void;
export const ggrsrenderer_getViewportChrome: (a: number, b: number, c: number, d: number) => void;
export const ggrsrenderer_info: (a: number, b: number) => void;
export const ggrsrenderer_initPlotStream: (a: number, b: number, c: number) => number;
export const ggrsrenderer_initView: (a: number, b: number, c: number, d: number) => void;
export const ggrsrenderer_initializeTercen: (a: number, b: number, c: number, d: number, e: number) => void;
export const ggrsrenderer_loadAndMapChunk: (a: number, b: number) => number;
export const ggrsrenderer_loadDataChunk: (a: number, b: number) => number;
export const ggrsrenderer_loadDataChunkPacked: (a: number, b: number) => number;
export const ggrsrenderer_new: (a: number, b: number) => number;
export const ggrsrenderer_pan: (a: number, b: number, c: number, d: number, e: number) => void;
export const ggrsrenderer_resetView: (a: number, b: number) => void;
export const ggrsrenderer_zoom: (a: number, b: number, c: number, d: number, e: number) => void;
export const __wasm_bindgen_func_elem_1011: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_996: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_36428: (a: number, b: number, c: number, d: number) => void;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export3: (a: number) => void;
export const __wbindgen_export4: (a: number, b: number, c: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
