name: api_test
publish_to: 'none'

environment:
  sdk: ^3.5.0

dependencies:
  sci_tercen_client:
    path: /home/thiago/workspaces/tercen/main/sci_tercen_client/sci_tercen_client
  stack_trace: ^1.11.0
